[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3.30", features = ["thread-pool"] }
tokio = { version = "1", features = ["full"] }
threadpool = "1.8.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.17"