#!/bin/bash

CONFIG_PATH="./src/config/config.yaml"

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --config=*)
            CONFIG_PATH="${1#*=}"
            ;;
        *)
            echo "Неизвестный параметр: $1"
            exit 1
            ;;
    esac
    shift
done

echo "// Code generated by "jxs"; DO NOT EDIT.
pub const CONFIG_PATH: &str = \"$CONFIG_PATH\";" \
  > ./src/config/default.rs
