// Code generated by jxs; DO NOT EDIT.
pub const CONFIG_PATH: &str = "./jxs/config/config.yaml";
pub const ACCESS_LOG_PATH: &str = "/home/alexander/web_server/jxs/logs/access/";
pub const ERROR_LOG_PATH: &str = "/home/alexander/web_server/jxs/logs/error/";
