// Code generated by jxs; DO NOT EDIT.
pub const CONFIG_PATH: &str = "./src/config/config.yaml";
pub const ACCESS_LOG_PATH: &str = "/home/jxs-logs/access.log";
pub const ERROR_LOG_PATH: &str = "/home/jxs-logs/error.log";
